import { formatCurrencyFull, dayKey } from './format';

export interface StatementRow {
  name: string;
  detail: string;
  value: number;
}

export interface StatementData {
  name: string;
  month: number;
  economyPhase: string;
  netWorth: number;
  cash: number;
  investedValue: number;
  savings: number;
  depositsValue: number;
  loanBalance: number;
  businessesValue: number;
  propertiesValue: number;
  creditScore: number;
  realizedPnl: number;
  taxIncome: number;
  taxCapitalGains: number;
  holdings: StatementRow[];
}

function row(label: string, value: number) {
  return `<tr><td>${label}</td><td class="num">${formatCurrencyFull(value)}</td></tr>`;
}

/** Build a printable HTML financial statement and download it. Open the file
 *  and use the browser's Print → Save as PDF for a PDF report. */
export function downloadStatement(d: StatementData) {
  const holdingsRows = d.holdings.length
    ? d.holdings
        .map(
          (h) =>
            `<tr><td>${h.name}<span class="dim"> · ${h.detail}</span></td><td class="num">${formatCurrencyFull(h.value)}</td></tr>`
        )
        .join('')
    : `<tr><td colspan="2" class="dim">No holdings</td></tr>`;

  const html = `<!doctype html><html><head><meta charset="utf-8">
<title>Invest Master — Statement</title>
<style>
  :root { color-scheme: light; }
  body { font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; color: #0f172a; margin: 0; padding: 32px; background: #fff; }
  .wrap { max-width: 720px; margin: 0 auto; }
  h1 { font-size: 22px; margin: 0; }
  .brand { display:flex; align-items:center; gap:12px; margin-bottom: 4px; }
  .logo { width:40px; height:40px; border-radius:10px; background:linear-gradient(135deg,#6366f1,#8b5cf6); color:#fff; display:flex; align-items:center; justify-content:center; font-weight:800; font-size:22px; }
  .sub { color:#64748b; font-size: 12px; margin: 2px 0 20px; }
  .hero { background:#f1f5f9; border-radius:14px; padding:18px; margin-bottom:18px; }
  .hero .nw { font-size: 30px; font-weight: 800; }
  h2 { font-size: 14px; margin: 22px 0 8px; text-transform: uppercase; letter-spacing: .5px; color:#475569; }
  table { width:100%; border-collapse: collapse; font-size: 14px; }
  td { padding: 8px 4px; border-bottom: 1px solid #e2e8f0; }
  .num { text-align: right; font-variant-numeric: tabular-nums; font-weight: 600; }
  .dim { color:#94a3b8; font-weight: 400; }
  .foot { margin-top: 28px; font-size: 11px; color:#94a3b8; }
  @media print { body { padding: 0; } }
</style></head><body><div class="wrap">
  <div class="brand"><div class="logo">₹</div><div><h1>Invest Master</h1><div class="sub">Financial Statement · ${d.name} · Month ${d.month} · ${dayKey()}</div></div></div>
  <div class="hero"><div class="dim" style="font-size:12px">Total Net Worth</div><div class="nw">${formatCurrencyFull(d.netWorth)}</div><div class="dim" style="font-size:12px">Economy: ${d.economyPhase} · Credit score ${d.creditScore}</div></div>

  <h2>Assets</h2>
  <table>
    ${row('Cash', d.cash)}
    ${row('Investments', d.investedValue)}
    ${row('Savings', d.savings)}
    ${row('Fixed Deposits', d.depositsValue)}
    ${row('Businesses', d.businessesValue)}
    ${row('Real Estate', d.propertiesValue)}
  </table>

  <h2>Liabilities</h2>
  <table>${row('Outstanding Loans', d.loanBalance)}</table>

  <h2>Holdings</h2>
  <table>${holdingsRows}</table>

  <h2>Performance & Tax</h2>
  <table>
    ${row('Lifetime Realised P&L', d.realizedPnl)}
    ${row('Income Tax Paid', d.taxIncome)}
    ${row('Capital Gains Tax Paid', d.taxCapitalGains)}
  </table>

  <div class="foot">Simulation only — all values are virtual. Generated by Invest Master. Tip: use your browser's Print → Save as PDF to keep a PDF copy.</div>
</div>
<script>window.onload=function(){setTimeout(function(){try{window.print()}catch(e){}},300)}</script>
</body></html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `invest-master-statement-${dayKey()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}
